# Generated by Django 3.2.6 on 2021-08-18 05:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(blank=True, max_length=20)),
                ('nama_barang', models.CharField(blank=True, max_length=20)),
                ('kondisi_barang', models.CharField(blank=True, choices=[('Baik', 'Baik'), ('Rusak', 'Rusak')], max_length=30, null=True)),
                ('jenis_barang', models.CharField(blank=True, choices=[('Barang Masuk', 'Barang Masuk'), ('Barang Keluar', 'Barang Keluar'), ('Barang Rusak', 'Barang Rusak')], max_length=30, null=True)),
                ('kategori_barang', models.CharField(blank=True, choices=[('Barang Habis Pakai', 'Barang Habis Pakai'), ('Barang Tidak Habis Pakai', 'Barang Tidak Habis Pakai')], max_length=30, null=True)),
                ('tanggal', models.CharField(blank=True, max_length=20, null=True)),
                ('tgl_update', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Di Pinjam', 'Di Pinjam'), ('Di Kembalikan', 'Di Kembalikan'), ('Di Cek', 'Di Cek'), ('Di Pindah', 'Di Pindah')], max_length=20, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
                ('gambar', models.ImageField(blank=True, upload_to='foto')),
                ('qrcode', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
            options={
                'verbose_name_plural': 'Barang',
            },
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_ruangan', models.CharField(max_length=50)),
                ('nama_ruangan', models.CharField(max_length=50)),
                ('keterangan', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ruangan',
            },
        ),
        migrations.CreateModel(
            name='PindahBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangcapek', to='inventaris.barang')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lokasi', to='inventaris.ruangan')),
            ],
            options={
                'verbose_name_plural': 'PindahBarang',
            },
        ),
        migrations.CreateModel(
            name='Pimpinan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pimpinan', models.CharField(max_length=30)),
                ('nip_pimpinan', models.CharField(max_length=18)),
                ('jabatan', models.CharField(max_length=30)),
                ('tgl_lahir', models.CharField(max_length=30)),
                ('pendidikan', models.CharField(max_length=30)),
                ('pangkat_golongan', models.CharField(max_length=30)),
                ('jenkel', models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=30, null=True)),
                ('alamat_pimpinan', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('foto_pimpinan', models.ImageField(blank=True, default='fotokosong.jpg', upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pimpinan',
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('nip', models.CharField(max_length=18)),
                ('tempat_tanggal_lahir', models.CharField(max_length=50)),
                ('pendidikan', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=12)),
                ('status', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Kepala Sekolah', 'Kepala Sekolah')], max_length=30, null=True)),
                ('foto', models.ImageField(blank=True, default='fotokosong.jpg', upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Petugas',
            },
        ),
        migrations.CreateModel(
            name='Inventaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('Di Pinjam', 'Di Pinjam'), ('Di Kembalikan', 'Di Kembalikan')], max_length=150, null=True)),
                ('tanggalpinjam', models.DateField(default=datetime.datetime.now)),
                ('tanggalkembali', models.DateField(default=datetime.datetime.now)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaris', to='inventaris.barang')),
            ],
        ),
        migrations.CreateModel(
            name='CekBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('kode_barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaris.barang')),
            ],
            options={
                'verbose_name_plural': 'CekBarang',
            },
        ),
        migrations.AddField(
            model_name='barang',
            name='lokasi_barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaris.ruangan'),
        ),
    ]
