# Generated by Django 3.2.6 on 2021-08-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0004_alter_barang_lokasi_barang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='lokasi_barang',
            new_name='lokasi',
        ),
    ]
