# Generated by Django 3.2.6 on 2021-08-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0006_alter_barang_gambar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pimpinan',
        ),
    ]
