# Generated by Django 3.2.6 on 2021-08-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0007_delete_pimpinan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis_barang',
            field=models.CharField(blank=True, choices=[('Barang Masuk', 'Barang Masuk'), ('Barang Keluar', 'Barang Keluar')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='status',
            field=models.CharField(blank=True, choices=[('Di Pinjam', 'Di Pinjam'), ('Di Kembalikan', 'Di Kembalikan')], max_length=20, null=True),
        ),
    ]
